# The Load Balancer Block
host "10.28.189.138:8080" {
    proxy_set_header Host $host;
    proxy_pass http://10.28.189.138:9000;
    dist_policy round-robin
}

# The Local Bypass (For Laptop 1 to test itself)
host "127.0.0.1:8080" {
    proxy_pass http://127.0.0.1:9000;
}